git:
  depth: 10
notifications:
  email: false
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: node_js
node_js:
  - "6"
os:
  - linux
  - osx
env:
  - TARGET_ARCH=x64

script: 
  - 'npm run build'
  - 'npm run test'
  - 'npm run e2e'

branches:
  only:
    - dev
    - user-recognition