# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1

    - name: Install xvfb
      run: |
        sudo apt-get install -y xvfb \
        export DISPLAY=':99.0' \
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    # Runs a single command using the runners shell
    - name: install dependencies
      run: npm install

    # - name: Tests
    #   run: npm run test

    # - name: E2E tests
    #   run: npm run e2e
      
    - name: publish
      run: npm run web:prod

    - name: publish artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: show folders
        run: ls -la
      - name: Azure Storage upload
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az storage blob upload-batch -d '$web' -s dist --connection-string '${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}'